In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/timeseries_fall_risk_dataset.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Timestamp           15000 non-null  object 
 1   Acceleration_X      15000 non-null  float64
 2   Acceleration_Y      15000 non-null  float64
 3   Acceleration_Z      15000 non-null  float64
 4   Angular_Velocity_X  15000 non-null  float64
 5   Angular_Velocity_Y  15000 non-null  float64
 6   Angular_Velocity_Z  15000 non-null  float64
 7   Pressure_Left       15000 non-null  float64
 8   Pressure_Right      15000 non-null  float64
 9   Heart_Rate          15000 non-null  float64
 10  Body_Temperature    15000 non-null  float64
 11  Risk_Level_Updated  15000 non-null  object 
dtypes: float64(10), object(2)
memory usage: 1.4+ MB


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



In [ ]:
# 1️⃣ Load Dataset
df = pd.read_csv("timeseries_fall_risk_dataset.csv")



In [ ]:
# 2️⃣ Convert Timestamp to datetime
df["Timestamp"] = pd.to_datetime(df["Timestamp"])



In [ ]:
# 3️⃣ Encode Risk Level Labels (Low = 0, Moderate = 1, High = 2)
label_encoder = LabelEncoder()
df["Risk_Level_Updated"] = label_encoder.fit_transform(df["Risk_Level_Updated"])

# 4️⃣ Select Features & Target
X = df.drop(columns=["Timestamp", "Risk_Level_Updated"])  # Features
y = df["Risk_Level_Updated"]  # Target Variable


In [ ]:

# 5️⃣ Split Data (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 6️⃣ Train Random Forest Model
rf_model = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)

# 7️⃣ Predictions
y_pred = rf_model.predict(X_test)

# 8️⃣ Evaluate Model
accuracy = accuracy_score(y_test, y_pred)
print(f"✅ Model Accuracy: {accuracy:.4f}")
print("📌 Classification Report:\n", classification_report(y_test, y_pred))
print("📊 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# 9️⃣ Feature Importance
feature_importance = pd.Series(rf_model.feature_importances_, index=X.columns)
print("🔍 Top Features Affecting Fall Risk:\n", feature_importance.sort_values(ascending=False))


✅ Model Accuracy: 1.0000
📌 Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       993
           1       1.00      1.00      1.00      1037
           2       1.00      1.00      1.00       970

    accuracy                           1.00      3000
   macro avg       1.00      1.00      1.00      3000
weighted avg       1.00      1.00      1.00      3000

📊 Confusion Matrix:
 [[ 993    0    0]
 [   0 1037    0]
 [   0    0  970]]
🔍 Top Features Affecting Fall Risk:
 Body_Temperature      0.435810
Heart_Rate            0.387578
Pressure_Left         0.093483
Pressure_Right        0.055601
Angular_Velocity_X    0.006916
Angular_Velocity_Z    0.005883
Angular_Velocity_Y    0.005219
Acceleration_Z        0.004354
Acceleration_Y        0.003262
Acceleration_X        0.001893
dtype: float64


In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold, cross_val_score

# 1️⃣ Load Dataset
df = pd.read_csv("timeseries_fall_risk_dataset.csv")

# 2️⃣ Convert Timestamp to datetime
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

# 3️⃣ Encode Risk Level Labels (Low = 0, Moderate = 1, High = 2)
label_encoder = LabelEncoder()
df["Risk_Level_Updated"] = label_encoder.fit_transform(df["Risk_Level_Updated"])

# 4️⃣ Select Features & Target
X = df.drop(columns=["Timestamp", "Risk_Level_Updated"])  # Features
y = df["Risk_Level_Updated"]  # Target Variable

# 5️⃣ Set up Stratified K-Fold Cross-Validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# 6️⃣ Initialize Random Forest Classifier
rf_model = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)

# 7️⃣ Perform Cross-Validation
cv_scores = cross_val_score(rf_model, X, y, cv=cv, scoring="accuracy")

# 8️⃣ Print Results
print(f"✅ Cross-Validation Accuracy Scores: {cv_scores}")
print(f"📊 Average Accuracy: {np.mean(cv_scores):.4f}")
print(f"📉 Standard Deviation: {np.std(cv_scores):.4f}")


✅ Cross-Validation Accuracy Scores: [1. 1. 1. 1. 1.]
📊 Average Accuracy: 1.0000
📉 Standard Deviation: 0.0000


In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# 1️⃣ Load Dataset
df = pd.read_csv("timeseries_fall_risk_dataset.csv")

# 2️⃣ Convert Timestamp to datetime
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

# 3️⃣ Encode Risk Level Labels
label_encoder = LabelEncoder()
df["Risk_Level_Updated"] = label_encoder.fit_transform(df["Risk_Level_Updated"])

# 4️⃣ Select Features & Target
X = df.drop(columns=["Timestamp", "Risk_Level_Updated"])  # Features
y = df["Risk_Level_Updated"]  # Target Variable

# 5️⃣ Train-Test Split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 6️⃣ Train Random Forest Classifier
rf_model = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)

# 7️⃣ Test Data (Example Scenario)
sample_data = np.array([[5.0, 3.2, 0.5, 3.5, 4.1, 5.2, 20, 80, 140, 39.5]])  # Modify for different cases

# 8️⃣ Make Prediction
predicted_risk = rf_model.predict(sample_data)[0]  # Get single prediction

# 9️⃣ Convert Prediction to Meaningful Alert
risk_levels = {0: "🔵 Low Risk", 1: "🟠 Medium Risk", 2: "🔴 High Risk"}
alerts = {
    0: "✅ Safe, but caution needed. Take care! Maintain balance.",
    1: "⚠️ Warning! Possible fall risk. Hold a railing, avoid sudden movements.",
    2: "🚨 Critical! Fall is likely! Stop moving, sit down immediately!"
}

# 🔟 Display Output
print(f"📌 Predicted Risk Level: {risk_levels[predicted_risk]}")
print(f"🔹 Alert: {alerts[predicted_risk]}")


📌 Predicted Risk Level: 🔵 Low Risk
🔹 Alert: ✅ Safe, but caution needed. Take care! Maintain balance.


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
